/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  GetPreferencesApiV1PreferencesGetParams,
  PatchPreferencesApiV1PreferencesPatchParams,
  PreferenceResponse,
  PreferenceUpdate
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getPreferences = () => {
/**
 * GET /preferences?family_id={familyId} — member.
 * @summary Get Preferences
 */
const getPreferencesApiV1PreferencesGet = (
    params: GetPreferencesApiV1PreferencesGetParams,
 ) => {
      return customInstance<PreferenceResponse>(
      {url: `/api/v1/preferences`, method: 'GET',
        params
    },
      );
    }
  /**
 * PATCH /preferences?family_id={familyId} — member.
 * @summary Patch Preferences
 */
const patchPreferencesApiV1PreferencesPatch = (
    preferenceUpdate: PreferenceUpdate,
    params: PatchPreferencesApiV1PreferencesPatchParams,
 ) => {
      return customInstance<PreferenceResponse>(
      {url: `/api/v1/preferences`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: preferenceUpdate,
        params
    },
      );
    }
  return {getPreferencesApiV1PreferencesGet,patchPreferencesApiV1PreferencesPatch}};
export type GetPreferencesApiV1PreferencesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPreferences>['getPreferencesApiV1PreferencesGet']>>>
export type PatchPreferencesApiV1PreferencesPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPreferences>['patchPreferencesApiV1PreferencesPatch']>>>
