/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  MetricsResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getMetrics = () => {
/**
 * GET /metrics — operational metrics for monitoring dashboards. No auth.
 * @summary Get Metrics
 */
const getMetricsApiV1MetricsGet = (
    
 ) => {
      return customInstance<MetricsResponse>(
      {url: `/api/v1/metrics`, method: 'GET'
    },
      );
    }
  return {getMetricsApiV1MetricsGet}};
export type GetMetricsApiV1MetricsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getMetrics>['getMetricsApiV1MetricsGet']>>>
