/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  FamilyCreate,
  FamilyResponse,
  JoinRequest,
  MemberAdd,
  MemberResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getFamilies = () => {
/**
 * POST /families — any authenticated user.
 * @summary Create Family
 */
const createFamilyApiV1FamiliesPost = (
    familyCreate: FamilyCreate,
 ) => {
      return customInstance<FamilyResponse>(
      {url: `/api/v1/families`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: familyCreate
    },
      );
    }
  /**
 * POST /families/{familyId}/join — member invite flow.
 * @summary Join Family
 */
const joinFamilyApiV1FamiliesFamilyIdJoinPost = (
    familyId: string,
    joinRequest: JoinRequest,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinRequest
    },
      );
    }
  /**
 * POST /families/{familyId}/members — guardian_only.
 * @summary Add Member
 */
const addMemberApiV1FamiliesFamilyIdMembersPost = (
    familyId: string,
    memberAdd: MemberAdd,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: memberAdd
    },
      );
    }
  /**
 * DELETE /families/{familyId}/members/{userId} — guardian_only.
 * @summary Remove Member
 */
const removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete = (
    familyId: string,
    userId: string,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/members/${userId}`, method: 'DELETE'
    },
      );
    }
  return {createFamilyApiV1FamiliesPost,joinFamilyApiV1FamiliesFamilyIdJoinPost,addMemberApiV1FamiliesFamilyIdMembersPost,removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete}};
export type CreateFamilyApiV1FamiliesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['createFamilyApiV1FamiliesPost']>>>
export type JoinFamilyApiV1FamiliesFamilyIdJoinPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['joinFamilyApiV1FamiliesFamilyIdJoinPost']>>>
export type AddMemberApiV1FamiliesFamilyIdMembersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['addMemberApiV1FamiliesFamilyIdMembersPost']>>>
export type RemoveMemberApiV1FamiliesFamilyIdMembersUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete']>>>
