/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  FamilyCreate,
  FamilyResponse,
  JoinRequest,
  ListMembersApiV1FamiliesFamilyIdMembersGetParams,
  MemberAdd,
  MemberCreateAndAdd,
  MemberDetail,
  MemberResponse,
  PaginatedResponseMemberDetail
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getFamilies = () => {
/**
 * POST /families — any authenticated user.
 * @summary Create Family
 */
const createFamilyApiV1FamiliesPost = (
    familyCreate: FamilyCreate,
 ) => {
      return customInstance<FamilyResponse>(
      {url: `/api/v1/families`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: familyCreate
    },
      );
    }
  /**
 * GET /families/{familyId} — any family member.
 * @summary Get Family
 */
const getFamilyApiV1FamiliesFamilyIdGet = (
    familyId: string,
 ) => {
      return customInstance<FamilyResponse>(
      {url: `/api/v1/families/${familyId}`, method: 'GET'
    },
      );
    }
  /**
 * POST /families/join — join a family using only an invite code.
 * @summary Join Family By Code
 */
const joinFamilyByCodeApiV1FamiliesJoinPost = (
    joinRequest: JoinRequest,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinRequest
    },
      );
    }
  /**
 * POST /families/{familyId}/join — member invite flow (legacy).
 * @summary Join Family
 */
const joinFamilyApiV1FamiliesFamilyIdJoinPost = (
    familyId: string,
    joinRequest: JoinRequest,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/join`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: joinRequest
    },
      );
    }
  /**
 * POST /families/{familyId}/members — guardian_only.
 * @summary Add Member
 */
const addMemberApiV1FamiliesFamilyIdMembersPost = (
    familyId: string,
    memberAdd: MemberAdd,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/members`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: memberAdd
    },
      );
    }
  /**
 * GET /families/{familyId}/members — any family member.
 * @summary List Members
 */
const listMembersApiV1FamiliesFamilyIdMembersGet = (
    familyId: string,
    params?: ListMembersApiV1FamiliesFamilyIdMembersGetParams,
 ) => {
      return customInstance<PaginatedResponseMemberDetail>(
      {url: `/api/v1/families/${familyId}/members`, method: 'GET',
        params
    },
      );
    }
  /**
 * POST /families/{familyId}/members/create — guardian_only. Creates a new user and adds them.
 * @summary Create And Add Member
 */
const createAndAddMemberApiV1FamiliesFamilyIdMembersCreatePost = (
    familyId: string,
    memberCreateAndAdd: MemberCreateAndAdd,
 ) => {
      return customInstance<MemberDetail>(
      {url: `/api/v1/families/${familyId}/members/create`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: memberCreateAndAdd
    },
      );
    }
  /**
 * DELETE /families/{familyId}/members/{userId} — guardian_only.
 * @summary Remove Member
 */
const removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete = (
    familyId: string,
    userId: string,
 ) => {
      return customInstance<MemberResponse>(
      {url: `/api/v1/families/${familyId}/members/${userId}`, method: 'DELETE'
    },
      );
    }
  return {createFamilyApiV1FamiliesPost,getFamilyApiV1FamiliesFamilyIdGet,joinFamilyByCodeApiV1FamiliesJoinPost,joinFamilyApiV1FamiliesFamilyIdJoinPost,addMemberApiV1FamiliesFamilyIdMembersPost,listMembersApiV1FamiliesFamilyIdMembersGet,createAndAddMemberApiV1FamiliesFamilyIdMembersCreatePost,removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete}};
export type CreateFamilyApiV1FamiliesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['createFamilyApiV1FamiliesPost']>>>
export type GetFamilyApiV1FamiliesFamilyIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['getFamilyApiV1FamiliesFamilyIdGet']>>>
export type JoinFamilyByCodeApiV1FamiliesJoinPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['joinFamilyByCodeApiV1FamiliesJoinPost']>>>
export type JoinFamilyApiV1FamiliesFamilyIdJoinPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['joinFamilyApiV1FamiliesFamilyIdJoinPost']>>>
export type AddMemberApiV1FamiliesFamilyIdMembersPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['addMemberApiV1FamiliesFamilyIdMembersPost']>>>
export type ListMembersApiV1FamiliesFamilyIdMembersGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['listMembersApiV1FamiliesFamilyIdMembersGet']>>>
export type CreateAndAddMemberApiV1FamiliesFamilyIdMembersCreatePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['createAndAddMemberApiV1FamiliesFamilyIdMembersCreatePost']>>>
export type RemoveMemberApiV1FamiliesFamilyIdMembersUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getFamilies>['removeMemberApiV1FamiliesFamilyIdMembersUserIdDelete']>>>
