/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  AbuseReportCreate,
  AbuseReportResponse,
  BlockCreate,
  BlockResponse,
  BlockUpdate,
  ListBlocksApiV1BlocksGetParams,
  PaginatedResponseBlockResponse,
  RelationshipResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getSafety = () => {
/**
 * POST /abuse-reports — member.
 * @summary Create Abuse Report
 */
const createAbuseReportApiV1AbuseReportsPost = (
    abuseReportCreate: AbuseReportCreate,
 ) => {
      return customInstance<AbuseReportResponse>(
      {url: `/api/v1/abuse-reports`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: abuseReportCreate
    },
      );
    }
  /**
 * GET /abuse-reports/{reportId} — reporter_or_guardian.
 * @summary Get Abuse Report
 */
const getAbuseReportApiV1AbuseReportsReportIdGet = (
    reportId: string,
 ) => {
      return customInstance<AbuseReportResponse>(
      {url: `/api/v1/abuse-reports/${reportId}`, method: 'GET'
    },
      );
    }
  /**
 * GET /blocks — list blocks created by the current user.
 * @summary List Blocks
 */
const listBlocksApiV1BlocksGet = (
    params?: ListBlocksApiV1BlocksGetParams,
 ) => {
      return customInstance<PaginatedResponseBlockResponse>(
      {url: `/api/v1/blocks`, method: 'GET',
        params
    },
      );
    }
  /**
 * POST /blocks — member.
 * @summary Create Block
 */
const createBlockApiV1BlocksPost = (
    blockCreate: BlockCreate,
 ) => {
      return customInstance<BlockResponse>(
      {url: `/api/v1/blocks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: blockCreate
    },
      );
    }
  /**
 * PATCH /blocks/{blockId} — member owner.
 * @summary Update Block
 */
const updateBlockApiV1BlocksBlockIdPatch = (
    blockId: string,
    blockUpdate: BlockUpdate,
 ) => {
      return customInstance<BlockResponse>(
      {url: `/api/v1/blocks/${blockId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: blockUpdate
    },
      );
    }
  /**
 * POST /relationships/{relationshipId}/suspend — party_only.
 * @summary Suspend Relationship
 */
const suspendRelationshipApiV1RelationshipsRelationshipIdSuspendPost = (
    relationshipId: string,
 ) => {
      return customInstance<RelationshipResponse>(
      {url: `/api/v1/relationships/${relationshipId}/suspend`, method: 'POST'
    },
      );
    }
  return {createAbuseReportApiV1AbuseReportsPost,getAbuseReportApiV1AbuseReportsReportIdGet,listBlocksApiV1BlocksGet,createBlockApiV1BlocksPost,updateBlockApiV1BlocksBlockIdPatch,suspendRelationshipApiV1RelationshipsRelationshipIdSuspendPost}};
export type CreateAbuseReportApiV1AbuseReportsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['createAbuseReportApiV1AbuseReportsPost']>>>
export type GetAbuseReportApiV1AbuseReportsReportIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['getAbuseReportApiV1AbuseReportsReportIdGet']>>>
export type ListBlocksApiV1BlocksGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['listBlocksApiV1BlocksGet']>>>
export type CreateBlockApiV1BlocksPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['createBlockApiV1BlocksPost']>>>
export type UpdateBlockApiV1BlocksBlockIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['updateBlockApiV1BlocksBlockIdPatch']>>>
export type SuspendRelationshipApiV1RelationshipsRelationshipIdSuspendPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSafety>['suspendRelationshipApiV1RelationshipsRelationshipIdSuspendPost']>>>
