/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  ConnectionInvite,
  ConnectionResponse,
  ConnectionTrustUpdate,
  ListConnectionsApiV1ConnectionsGetParams,
  ListPendingInvitesApiV1ConnectionsPendingGetParams,
  PaginatedResponseConnectionResponse,
  TrustedConnectionChild
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getConnections = () => {
/**
 * POST /connections/invite — send connection invite by email.
 * @summary Invite Connection
 */
const inviteConnectionApiV1ConnectionsInvitePost = (
    connectionInvite: ConnectionInvite,
 ) => {
      return customInstance<ConnectionResponse>(
      {url: `/api/v1/connections/invite`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: connectionInvite
    },
      );
    }
  /**
 * GET /connections — list my connections (optionally filter by status).
 * @summary List Connections
 */
const listConnectionsApiV1ConnectionsGet = (
    params?: ListConnectionsApiV1ConnectionsGetParams,
 ) => {
      return customInstance<PaginatedResponseConnectionResponse>(
      {url: `/api/v1/connections`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /connections/pending — invites sent TO me.
 * @summary List Pending Invites
 */
const listPendingInvitesApiV1ConnectionsPendingGet = (
    params?: ListPendingInvitesApiV1ConnectionsPendingGetParams,
 ) => {
      return customInstance<PaginatedResponseConnectionResponse>(
      {url: `/api/v1/connections/pending`, method: 'GET',
        params
    },
      );
    }
  /**
 * POST /connections/{id}/accept — accept invite.
 * @summary Accept Connection
 */
const acceptConnectionApiV1ConnectionsConnectionIdAcceptPost = (
    connectionId: string,
 ) => {
      return customInstance<ConnectionResponse>(
      {url: `/api/v1/connections/${connectionId}/accept`, method: 'POST'
    },
      );
    }
  /**
 * POST /connections/{id}/decline — decline invite.
 * @summary Decline Connection
 */
const declineConnectionApiV1ConnectionsConnectionIdDeclinePost = (
    connectionId: string,
 ) => {
      return customInstance<ConnectionResponse>(
      {url: `/api/v1/connections/${connectionId}/decline`, method: 'POST'
    },
      );
    }
  /**
 * POST /connections/{id}/revoke — either party revokes.
 * @summary Revoke Connection
 */
const revokeConnectionApiV1ConnectionsConnectionIdRevokePost = (
    connectionId: string,
 ) => {
      return customInstance<ConnectionResponse>(
      {url: `/api/v1/connections/${connectionId}/revoke`, method: 'POST'
    },
      );
    }
  /**
 * PATCH /connections/{id}/trust — toggle trusted flag.
 * @summary Update Connection Trust
 */
const updateConnectionTrustApiV1ConnectionsConnectionIdTrustPatch = (
    connectionId: string,
    connectionTrustUpdate: ConnectionTrustUpdate,
 ) => {
      return customInstance<ConnectionResponse>(
      {url: `/api/v1/connections/${connectionId}/trust`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: connectionTrustUpdate
    },
      );
    }
  /**
 * GET /connections/{id}/children — list naggable children via trusted connection.
 * @summary List Trusted Children
 */
const listTrustedChildrenApiV1ConnectionsConnectionIdChildrenGet = (
    connectionId: string,
 ) => {
      return customInstance<TrustedConnectionChild[]>(
      {url: `/api/v1/connections/${connectionId}/children`, method: 'GET'
    },
      );
    }
  return {inviteConnectionApiV1ConnectionsInvitePost,listConnectionsApiV1ConnectionsGet,listPendingInvitesApiV1ConnectionsPendingGet,acceptConnectionApiV1ConnectionsConnectionIdAcceptPost,declineConnectionApiV1ConnectionsConnectionIdDeclinePost,revokeConnectionApiV1ConnectionsConnectionIdRevokePost,updateConnectionTrustApiV1ConnectionsConnectionIdTrustPatch,listTrustedChildrenApiV1ConnectionsConnectionIdChildrenGet}};
export type InviteConnectionApiV1ConnectionsInvitePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['inviteConnectionApiV1ConnectionsInvitePost']>>>
export type ListConnectionsApiV1ConnectionsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['listConnectionsApiV1ConnectionsGet']>>>
export type ListPendingInvitesApiV1ConnectionsPendingGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['listPendingInvitesApiV1ConnectionsPendingGet']>>>
export type AcceptConnectionApiV1ConnectionsConnectionIdAcceptPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['acceptConnectionApiV1ConnectionsConnectionIdAcceptPost']>>>
export type DeclineConnectionApiV1ConnectionsConnectionIdDeclinePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['declineConnectionApiV1ConnectionsConnectionIdDeclinePost']>>>
export type RevokeConnectionApiV1ConnectionsConnectionIdRevokePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['revokeConnectionApiV1ConnectionsConnectionIdRevokePost']>>>
export type UpdateConnectionTrustApiV1ConnectionsConnectionIdTrustPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['updateConnectionTrustApiV1ConnectionsConnectionIdTrustPatch']>>>
export type ListTrustedChildrenApiV1ConnectionsConnectionIdChildrenGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConnections>['listTrustedChildrenApiV1ConnectionsConnectionIdChildrenGet']>>>
