/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  FamilyMetricsResponse,
  GetFamilyMetricsApiV1ReportsFamilyMetricsGetParams,
  GetWeeklyReportApiV1ReportsFamilyWeeklyGetParams,
  WeeklyReportResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getReports = () => {
/**
 * GET /reports/family/weekly?family_id={familyId} — guardian_only.
 * @summary Get Weekly Report
 */
const getWeeklyReportApiV1ReportsFamilyWeeklyGet = (
    params: GetWeeklyReportApiV1ReportsFamilyWeeklyGetParams,
 ) => {
      return customInstance<WeeklyReportResponse>(
      {url: `/api/v1/reports/family/weekly`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /reports/family/metrics?family_id={familyId}&from={date}&to={date} — guardian_only.
 * @summary Get Family Metrics
 */
const getFamilyMetricsApiV1ReportsFamilyMetricsGet = (
    params: GetFamilyMetricsApiV1ReportsFamilyMetricsGetParams,
 ) => {
      return customInstance<FamilyMetricsResponse>(
      {url: `/api/v1/reports/family/metrics`, method: 'GET',
        params
    },
      );
    }
  return {getWeeklyReportApiV1ReportsFamilyWeeklyGet,getFamilyMetricsApiV1ReportsFamilyMetricsGet}};
export type GetWeeklyReportApiV1ReportsFamilyWeeklyGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['getWeeklyReportApiV1ReportsFamilyWeeklyGet']>>>
export type GetFamilyMetricsApiV1ReportsFamilyMetricsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getReports>['getFamilyMetricsApiV1ReportsFamilyMetricsGet']>>>
