/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  EscalationResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getEscalation = () => {
/**
 * GET /nags/{nagId}/escalation — creator_or_guardian.
 * @summary Get Escalation
 */
const getEscalationApiV1NagsNagIdEscalationGet = (
    nagId: string,
 ) => {
      return customInstance<EscalationResponse>(
      {url: `/api/v1/nags/${nagId}/escalation`, method: 'GET'
    },
      );
    }
  /**
 * POST /nags/{nagId}/escalation/recompute — creator_or_guardian.
 * @summary Recompute Escalation
 */
const recomputeEscalationApiV1NagsNagIdEscalationRecomputePost = (
    nagId: string,
 ) => {
      return customInstance<EscalationResponse>(
      {url: `/api/v1/nags/${nagId}/escalation/recompute`, method: 'POST'
    },
      );
    }
  return {getEscalationApiV1NagsNagIdEscalationGet,recomputeEscalationApiV1NagsNagIdEscalationRecomputePost}};
export type GetEscalationApiV1NagsNagIdEscalationGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEscalation>['getEscalationApiV1NagsNagIdEscalationGet']>>>
export type RecomputeEscalationApiV1NagsNagIdEscalationRecomputePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getEscalation>['recomputeEscalationApiV1NagsNagIdEscalationRecomputePost']>>>
