/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeliveryResponse,
  ListDeliveriesApiV1DeliveriesGetParams
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getDeliveries = () => {
/**
 * GET /deliveries?nag_id={nagId} — creator_or_guardian.
 * @summary List Deliveries
 */
const listDeliveriesApiV1DeliveriesGet = (
    params: ListDeliveriesApiV1DeliveriesGetParams,
 ) => {
      return customInstance<DeliveryResponse[]>(
      {url: `/api/v1/deliveries`, method: 'GET',
        params
    },
      );
    }
  return {listDeliveriesApiV1DeliveriesGet}};
export type ListDeliveriesApiV1DeliveriesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDeliveries>['listDeliveriesApiV1DeliveriesGet']>>>
