/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  VersionResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getVersion = () => {
/**
 * GET /version — returns server, API, and minimum client versions. No auth required.
 * @summary Get Version
 */
const getVersionApiV1VersionGet = (
    
 ) => {
      return customInstance<VersionResponse>(
      {url: `/api/v1/version`, method: 'GET'
    },
      );
    }
  return {getVersionApiV1VersionGet}};
export type GetVersionApiV1VersionGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getVersion>['getVersionApiV1VersionGet']>>>
