/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  AuthResponse,
  ChildLoginRequest,
  LoginRequest,
  RefreshRequest,
  SignupRequest
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getAuth = () => {
/**
 * @summary Signup
 */
const signupApiV1AuthSignupPost = (
    signupRequest: SignupRequest,
 ) => {
      return customInstance<AuthResponse>(
      {url: `/api/v1/auth/signup`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: signupRequest
    },
      );
    }
  /**
 * @summary Login
 */
const loginApiV1AuthLoginPost = (
    loginRequest: LoginRequest,
 ) => {
      return customInstance<AuthResponse>(
      {url: `/api/v1/auth/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: loginRequest
    },
      );
    }
  /**
 * @summary Refresh
 */
const refreshApiV1AuthRefreshPost = (
    refreshRequest: RefreshRequest,
 ) => {
      return customInstance<AuthResponse>(
      {url: `/api/v1/auth/refresh`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  /**
 * Authenticate a child using family code + username + 4-digit PIN.
 * @summary Child Login
 */
const childLoginApiV1AuthChildLoginPost = (
    childLoginRequest: ChildLoginRequest,
 ) => {
      return customInstance<AuthResponse>(
      {url: `/api/v1/auth/child-login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: childLoginRequest
    },
      );
    }
  /**
 * @summary Logout
 */
const logoutApiV1AuthLogoutPost = (
    refreshRequest: RefreshRequest,
 ) => {
      return customInstance<void>(
      {url: `/api/v1/auth/logout`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: refreshRequest
    },
      );
    }
  return {signupApiV1AuthSignupPost,loginApiV1AuthLoginPost,refreshApiV1AuthRefreshPost,childLoginApiV1AuthChildLoginPost,logoutApiV1AuthLogoutPost}};
export type SignupApiV1AuthSignupPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['signupApiV1AuthSignupPost']>>>
export type LoginApiV1AuthLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['loginApiV1AuthLoginPost']>>>
export type RefreshApiV1AuthRefreshPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['refreshApiV1AuthRefreshPost']>>>
export type ChildLoginApiV1AuthChildLoginPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['childLoginApiV1AuthChildLoginPost']>>>
export type LogoutApiV1AuthLogoutPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAuth>['logoutApiV1AuthLogoutPost']>>>
