/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  ExcuseCreate,
  ExcuseResponse,
  ListExcusesApiV1NagsNagIdExcusesGetParams,
  ListNagsApiV1NagsGetParams,
  NagCreate,
  NagResponse,
  NagStatusUpdate,
  NagUpdate,
  PaginatedResponseExcuseResponse,
  PaginatedResponseNagResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getNags = () => {
/**
 * POST /nags — family or connection context.
 * @summary Create Nag
 */
const createNagApiV1NagsPost = (
    nagCreate: NagCreate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nagCreate
    },
      );
    }
  /**
 * GET /nags — optional family_id or connection_id filter.
 * @summary List Nags
 */
const listNagsApiV1NagsGet = (
    params?: ListNagsApiV1NagsGetParams,
 ) => {
      return customInstance<PaginatedResponseNagResponse>(
      {url: `/api/v1/nags`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /nags/{nagId} — creator_or_guardian or recipient.
 * @summary Get Nag
 */
const getNagApiV1NagsNagIdGet = (
    nagId: string,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}`, method: 'GET'
    },
      );
    }
  /**
 * PATCH /nags/{nagId} — creator_or_guardian, or recipient for committed_at only.
 * @summary Update Nag
 */
const updateNagApiV1NagsNagIdPatch = (
    nagId: string,
    nagUpdate: NagUpdate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: nagUpdate
    },
      );
    }
  /**
 * POST /nags/{nagId}/status — recipient_only.
 * @summary Update Nag Status
 */
const updateNagStatusApiV1NagsNagIdStatusPost = (
    nagId: string,
    nagStatusUpdate: NagStatusUpdate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nagStatusUpdate
    },
      );
    }
  /**
 * POST /nags/{nagId}/withdraw — creator_only, open→withdrawn.
 * @summary Withdraw Nag
 */
const withdrawNagApiV1NagsNagIdWithdrawPost = (
    nagId: string,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}/withdraw`, method: 'POST'
    },
      );
    }
  /**
 * POST /nags/{nagId}/dismiss — recipient_only, hides from recipient's view.
 * @summary Dismiss Nag
 */
const dismissNagApiV1NagsNagIdDismissPost = (
    nagId: string,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}/dismiss`, method: 'POST'
    },
      );
    }
  /**
 * POST /nags/{nagId}/undismiss — recipient_only, restores visibility.
 * @summary Undismiss Nag
 */
const undismissNagApiV1NagsNagIdUndismissPost = (
    nagId: string,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}/undismiss`, method: 'POST'
    },
      );
    }
  /**
 * POST /nags/{nagId}/excuses — recipient_only, requires_consent(ai_mediation).
 * @summary Submit Excuse
 */
const submitExcuseApiV1NagsNagIdExcusesPost = (
    nagId: string,
    excuseCreate: ExcuseCreate,
 ) => {
      return customInstance<ExcuseResponse>(
      {url: `/api/v1/nags/${nagId}/excuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: excuseCreate
    },
      );
    }
  /**
 * GET /nags/{nagId}/excuses — creator_or_guardian or recipient.
 * @summary List Excuses
 */
const listExcusesApiV1NagsNagIdExcusesGet = (
    nagId: string,
    params?: ListExcusesApiV1NagsNagIdExcusesGetParams,
 ) => {
      return customInstance<PaginatedResponseExcuseResponse>(
      {url: `/api/v1/nags/${nagId}/excuses`, method: 'GET',
        params
    },
      );
    }
  return {createNagApiV1NagsPost,listNagsApiV1NagsGet,getNagApiV1NagsNagIdGet,updateNagApiV1NagsNagIdPatch,updateNagStatusApiV1NagsNagIdStatusPost,withdrawNagApiV1NagsNagIdWithdrawPost,dismissNagApiV1NagsNagIdDismissPost,undismissNagApiV1NagsNagIdUndismissPost,submitExcuseApiV1NagsNagIdExcusesPost,listExcusesApiV1NagsNagIdExcusesGet}};
export type CreateNagApiV1NagsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['createNagApiV1NagsPost']>>>
export type ListNagsApiV1NagsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['listNagsApiV1NagsGet']>>>
export type GetNagApiV1NagsNagIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['getNagApiV1NagsNagIdGet']>>>
export type UpdateNagApiV1NagsNagIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['updateNagApiV1NagsNagIdPatch']>>>
export type UpdateNagStatusApiV1NagsNagIdStatusPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['updateNagStatusApiV1NagsNagIdStatusPost']>>>
export type WithdrawNagApiV1NagsNagIdWithdrawPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['withdrawNagApiV1NagsNagIdWithdrawPost']>>>
export type DismissNagApiV1NagsNagIdDismissPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['dismissNagApiV1NagsNagIdDismissPost']>>>
export type UndismissNagApiV1NagsNagIdUndismissPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['undismissNagApiV1NagsNagIdUndismissPost']>>>
export type SubmitExcuseApiV1NagsNagIdExcusesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['submitExcuseApiV1NagsNagIdExcusesPost']>>>
export type ListExcusesApiV1NagsNagIdExcusesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['listExcusesApiV1NagsNagIdExcusesGet']>>>
