/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  ExcuseCreate,
  ListNagsApiV1NagsGetParams,
  NagCreate,
  NagResponse,
  NagStatusUpdate,
  NagUpdate
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getNags = () => {
/**
 * POST /nags — creator_or_guardian.
 * @summary Create Nag
 */
const createNagApiV1NagsPost = (
    nagCreate: NagCreate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nagCreate
    },
      );
    }
  /**
 * GET /nags?family_id={familyId}&state={state} — member.
 * @summary List Nags
 */
const listNagsApiV1NagsGet = (
    params: ListNagsApiV1NagsGetParams,
 ) => {
      return customInstance<NagResponse[]>(
      {url: `/api/v1/nags`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /nags/{nagId} — creator_or_guardian or recipient.
 * @summary Get Nag
 */
const getNagApiV1NagsNagIdGet = (
    nagId: string,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}`, method: 'GET'
    },
      );
    }
  /**
 * PATCH /nags/{nagId} — creator_or_guardian.
 * @summary Update Nag
 */
const updateNagApiV1NagsNagIdPatch = (
    nagId: string,
    nagUpdate: NagUpdate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: nagUpdate
    },
      );
    }
  /**
 * POST /nags/{nagId}/status — recipient_only.
 * @summary Update Nag Status
 */
const updateNagStatusApiV1NagsNagIdStatusPost = (
    nagId: string,
    nagStatusUpdate: NagStatusUpdate,
 ) => {
      return customInstance<NagResponse>(
      {url: `/api/v1/nags/${nagId}/status`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: nagStatusUpdate
    },
      );
    }
  /**
 * POST /nags/{nagId}/excuses — recipient_only, requires_consent(ai_mediation).
 * @summary Submit Excuse
 */
const submitExcuseApiV1NagsNagIdExcusesPost = (
    nagId: string,
    excuseCreate: ExcuseCreate,
 ) => {
      return customInstance<unknown>(
      {url: `/api/v1/nags/${nagId}/excuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: excuseCreate
    },
      );
    }
  /**
 * GET /nags/{nagId}/excuses — creator_or_guardian or recipient.
 * @summary List Excuses
 */
const listExcusesApiV1NagsNagIdExcusesGet = (
    nagId: string,
 ) => {
      return customInstance<unknown>(
      {url: `/api/v1/nags/${nagId}/excuses`, method: 'GET'
    },
      );
    }
  return {createNagApiV1NagsPost,listNagsApiV1NagsGet,getNagApiV1NagsNagIdGet,updateNagApiV1NagsNagIdPatch,updateNagStatusApiV1NagsNagIdStatusPost,submitExcuseApiV1NagsNagIdExcusesPost,listExcusesApiV1NagsNagIdExcusesGet}};
export type CreateNagApiV1NagsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['createNagApiV1NagsPost']>>>
export type ListNagsApiV1NagsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['listNagsApiV1NagsGet']>>>
export type GetNagApiV1NagsNagIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['getNagApiV1NagsNagIdGet']>>>
export type UpdateNagApiV1NagsNagIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['updateNagApiV1NagsNagIdPatch']>>>
export type UpdateNagStatusApiV1NagsNagIdStatusPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['updateNagStatusApiV1NagsNagIdStatusPost']>>>
export type SubmitExcuseApiV1NagsNagIdExcusesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['submitExcuseApiV1NagsNagIdExcusesPost']>>>
export type ListExcusesApiV1NagsNagIdExcusesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getNags>['listExcusesApiV1NagsNagIdExcusesGet']>>>
