/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  ConsentCreate,
  ConsentResponse,
  ConsentUpdate,
  ListConsentsApiV1ConsentsGetParams,
  PaginatedResponseConsentResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getConsents = () => {
/**
 * GET /consents?family_id={familyId} — member.
 * @summary List Consents
 */
const listConsentsApiV1ConsentsGet = (
    params: ListConsentsApiV1ConsentsGetParams,
 ) => {
      return customInstance<PaginatedResponseConsentResponse>(
      {url: `/api/v1/consents`, method: 'GET',
        params
    },
      );
    }
  /**
 * POST /consents — member or guardian.
 * @summary Create Consent
 */
const createConsentApiV1ConsentsPost = (
    consentCreate: ConsentCreate,
 ) => {
      return customInstance<ConsentResponse>(
      {url: `/api/v1/consents`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: consentCreate
    },
      );
    }
  /**
 * PATCH /consents/{consentId} — member or guardian.
 * @summary Update Consent
 */
const updateConsentApiV1ConsentsConsentIdPatch = (
    consentId: string,
    consentUpdate: ConsentUpdate,
 ) => {
      return customInstance<ConsentResponse>(
      {url: `/api/v1/consents/${consentId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: consentUpdate
    },
      );
    }
  return {listConsentsApiV1ConsentsGet,createConsentApiV1ConsentsPost,updateConsentApiV1ConsentsConsentIdPatch}};
export type ListConsentsApiV1ConsentsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConsents>['listConsentsApiV1ConsentsGet']>>>
export type CreateConsentApiV1ConsentsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConsents>['createConsentApiV1ConsentsPost']>>>
export type UpdateConsentApiV1ConsentsConsentIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getConsents>['updateConsentApiV1ConsentsConsentIdPatch']>>>
