/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  CoachingRequest,
  CoachingResponse,
  DigestApiV1AiDigestGetParams,
  DigestResponse,
  ExcuseSummaryRequest,
  ExcuseSummaryResponse,
  PatternsApiV1AiPatternsGetParams,
  PatternsResponse,
  PredictCompletionApiV1AiPredictCompletionGetParams,
  PredictCompletionResponse,
  PushBackRequest,
  PushBackResponse,
  ToneSelectRequest,
  ToneSelectResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getAi = () => {
/**
 * @summary Summarize Excuse
 */
const summarizeExcuseApiV1AiSummarizeExcusePost = (
    excuseSummaryRequest: ExcuseSummaryRequest,
 ) => {
      return customInstance<ExcuseSummaryResponse>(
      {url: `/api/v1/ai/summarize-excuse`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: excuseSummaryRequest
    },
      );
    }
  /**
 * @summary Select Tone
 */
const selectToneApiV1AiSelectTonePost = (
    toneSelectRequest: ToneSelectRequest,
 ) => {
      return customInstance<ToneSelectResponse>(
      {url: `/api/v1/ai/select-tone`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: toneSelectRequest
    },
      );
    }
  /**
 * @summary Coaching
 */
const coachingApiV1AiCoachingPost = (
    coachingRequest: CoachingRequest,
 ) => {
      return customInstance<CoachingResponse>(
      {url: `/api/v1/ai/coaching`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: coachingRequest
    },
      );
    }
  /**
 * @summary Patterns
 */
const patternsApiV1AiPatternsGet = (
    params: PatternsApiV1AiPatternsGetParams,
 ) => {
      return customInstance<PatternsResponse>(
      {url: `/api/v1/ai/patterns`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Digest
 */
const digestApiV1AiDigestGet = (
    params: DigestApiV1AiDigestGetParams,
 ) => {
      return customInstance<DigestResponse>(
      {url: `/api/v1/ai/digest`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Predict Completion
 */
const predictCompletionApiV1AiPredictCompletionGet = (
    params: PredictCompletionApiV1AiPredictCompletionGetParams,
 ) => {
      return customInstance<PredictCompletionResponse>(
      {url: `/api/v1/ai/predict-completion`, method: 'GET',
        params
    },
      );
    }
  /**
 * @summary Push Back
 */
const pushBackApiV1AiPushBackPost = (
    pushBackRequest: PushBackRequest,
 ) => {
      return customInstance<PushBackResponse>(
      {url: `/api/v1/ai/push-back`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pushBackRequest
    },
      );
    }
  return {summarizeExcuseApiV1AiSummarizeExcusePost,selectToneApiV1AiSelectTonePost,coachingApiV1AiCoachingPost,patternsApiV1AiPatternsGet,digestApiV1AiDigestGet,predictCompletionApiV1AiPredictCompletionGet,pushBackApiV1AiPushBackPost}};
export type SummarizeExcuseApiV1AiSummarizeExcusePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['summarizeExcuseApiV1AiSummarizeExcusePost']>>>
export type SelectToneApiV1AiSelectTonePostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['selectToneApiV1AiSelectTonePost']>>>
export type CoachingApiV1AiCoachingPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['coachingApiV1AiCoachingPost']>>>
export type PatternsApiV1AiPatternsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['patternsApiV1AiPatternsGet']>>>
export type DigestApiV1AiDigestGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['digestApiV1AiDigestGet']>>>
export type PredictCompletionApiV1AiPredictCompletionGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['predictCompletionApiV1AiPredictCompletionGet']>>>
export type PushBackApiV1AiPushBackPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAi>['pushBackApiV1AiPushBackPost']>>>
