/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  IncentiveRuleCreate,
  IncentiveRuleResponse,
  IncentiveRuleUpdate,
  ListIncentiveEventsApiV1IncentiveEventsGetParams,
  ListIncentiveRulesApiV1IncentiveRulesGetParams,
  PaginatedResponseIncentiveEventResponse,
  PaginatedResponseIncentiveRuleResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getIncentives = () => {
/**
 * GET /incentive-rules?family_id={familyId} — guardian_only.
 * @summary List Incentive Rules
 */
const listIncentiveRulesApiV1IncentiveRulesGet = (
    params: ListIncentiveRulesApiV1IncentiveRulesGetParams,
 ) => {
      return customInstance<PaginatedResponseIncentiveRuleResponse>(
      {url: `/api/v1/incentive-rules`, method: 'GET',
        params
    },
      );
    }
  /**
 * POST /incentive-rules — guardian_only.
 * @summary Create Incentive Rule
 */
const createIncentiveRuleApiV1IncentiveRulesPost = (
    incentiveRuleCreate: IncentiveRuleCreate,
 ) => {
      return customInstance<IncentiveRuleResponse>(
      {url: `/api/v1/incentive-rules`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: incentiveRuleCreate
    },
      );
    }
  /**
 * PATCH /incentive-rules/{ruleId} — guardian_only.
 * @summary Update Incentive Rule
 */
const updateIncentiveRuleApiV1IncentiveRulesRuleIdPatch = (
    ruleId: string,
    incentiveRuleUpdate: IncentiveRuleUpdate,
 ) => {
      return customInstance<IncentiveRuleResponse>(
      {url: `/api/v1/incentive-rules/${ruleId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: incentiveRuleUpdate
    },
      );
    }
  /**
 * GET /incentive-events?nag_id={nagId} — guardian_only.
 * @summary List Incentive Events
 */
const listIncentiveEventsApiV1IncentiveEventsGet = (
    params: ListIncentiveEventsApiV1IncentiveEventsGetParams,
 ) => {
      return customInstance<PaginatedResponseIncentiveEventResponse>(
      {url: `/api/v1/incentive-events`, method: 'GET',
        params
    },
      );
    }
  return {listIncentiveRulesApiV1IncentiveRulesGet,createIncentiveRuleApiV1IncentiveRulesPost,updateIncentiveRuleApiV1IncentiveRulesRuleIdPatch,listIncentiveEventsApiV1IncentiveEventsGet}};
export type ListIncentiveRulesApiV1IncentiveRulesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIncentives>['listIncentiveRulesApiV1IncentiveRulesGet']>>>
export type CreateIncentiveRuleApiV1IncentiveRulesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIncentives>['createIncentiveRuleApiV1IncentiveRulesPost']>>>
export type UpdateIncentiveRuleApiV1IncentiveRulesRuleIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIncentives>['updateIncentiveRuleApiV1IncentiveRulesRuleIdPatch']>>>
export type ListIncentiveEventsApiV1IncentiveEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getIncentives>['listIncentiveEventsApiV1IncentiveEventsGet']>>>
