/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  SyncEventsApiV1SyncEventsGetParams,
  SyncResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getSync = () => {
/**
 * Incremental sync endpoint for iOS local event cache.

Returns nags, nag_events, ai_mediation_events, and gamification_events
that were created/updated since the given timestamp for the specified family.
 * @summary Sync Events
 */
const syncEventsApiV1SyncEventsGet = (
    params: SyncEventsApiV1SyncEventsGetParams,
 ) => {
      return customInstance<SyncResponse>(
      {url: `/api/v1/sync/events`, method: 'GET',
        params
    },
      );
    }
  return {syncEventsApiV1SyncEventsGet}};
export type SyncEventsApiV1SyncEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getSync>['syncEventsApiV1SyncEventsGet']>>>
