/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface AbuseReportCreate {
  target_id: string;
  /**
   * @minLength 1
   * @maxLength 2000
   */
  reason: string;
}
