/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type AbuseReportStatus = typeof AbuseReportStatus[keyof typeof AbuseReportStatus];


export const AbuseReportStatus = {
  open: 'open',
  investigating: 'investigating',
  resolved: 'resolved',
  dismissed: 'dismissed',
} as const;
