/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { AbuseReportStatus } from './abuseReportStatus';

export interface AbuseReportResponse {
  id: string;
  reporter_id: string;
  target_id: string;
  reason: string;
  status: AbuseReportStatus;
}
