/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export interface AccountResponse {
  id: string;
  email: string | null;
  display_name: string | null;
  status: string;
  created_at: string;
}
