/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type AITone = typeof AITone[keyof typeof AITone];


export const AITone = {
  neutral: 'neutral',
  supportive: 'supportive',
  firm: 'firm',
} as const;
