/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface ApprovalResponse {
  id: string;
  policy_id: string;
  approver_id: string;
  approved_at: string;
  comment: string | null;
}
