/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { AccountResponse } from './accountResponse';

export interface AuthResponse {
  access_token: string;
  refresh_token: string;
  token_type?: string;
  user: AccountResponse;
  family_id?: string | null;
  family_role?: string | null;
}
