/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type BadgeType = typeof BadgeType[keyof typeof BadgeType];


export const BadgeType = {
  first_completion: 'first_completion',
  streak_3: 'streak_3',
  streak_7: 'streak_7',
  streak_30: 'streak_30',
  perfect_week: 'perfect_week',
  century_club: 'century_club',
} as const;
