/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { BadgeType } from './badgeType';

export interface BadgeResponse {
  id: string;
  user_id: string;
  family_id: string;
  badge_type: BadgeType;
  earned_at: string;
}
