/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type BlockState = typeof BlockState[keyof typeof BlockState];


export const BlockState = {
  active: 'active',
  lifted: 'lifted',
} as const;
