/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { BlockState } from './blockState';

export interface BlockResponse {
  id: string;
  actor_id: string;
  target_id: string;
  state: BlockState;
}
