/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface ChildSettingsResponse {
  child_user_id: string;
  family_id: string;
  can_snooze: boolean;
  max_snoozes_per_day: number;
  can_submit_excuses: boolean;
  quiet_hours_start?: string | null;
  quiet_hours_end?: string | null;
}
