/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface ChildSettingsUpdate {
  can_snooze?: boolean | null;
  max_snoozes_per_day?: number | null;
  can_submit_excuses?: boolean | null;
  quiet_hours_start?: string | null;
  quiet_hours_end?: string | null;
}
