/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface ChildCredentialsSet {
  /**
   * @minLength 1
   * @maxLength 64
   */
  username: string;
  /**
   * @minLength 4
   * @maxLength 4
   * @pattern ^\d{4}$
   */
  pin: string;
}
