/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { ConnectionStatus } from './connectionStatus';

export interface ConnectionResponse {
  id: string;
  inviter_id: string;
  invitee_id?: string | null;
  invitee_email: string;
  status: ConnectionStatus;
  caregiver?: boolean;
  created_at: string;
  responded_at?: string | null;
  other_party_email?: string | null;
  other_party_display_name?: string | null;
}
