/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type ConsentType = typeof ConsentType[keyof typeof ConsentType];


export const ConsentType = {
  child_account_creation: 'child_account_creation',
  sms_opt_in: 'sms_opt_in',
  ai_mediation: 'ai_mediation',
  gamification_participation: 'gamification_participation',
} as const;
