/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { DeliveryChannel } from './deliveryChannel';
import type { DeliveryStatus } from './deliveryStatus';

export interface DeliveryResponse {
  id: string;
  nag_event_id: string;
  channel: DeliveryChannel;
  status: DeliveryStatus;
  provider_ref: string | null;
}
