/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type DeliveryChannel = typeof DeliveryChannel[keyof typeof DeliveryChannel];


export const DeliveryChannel = {
  push: 'push',
  sms: 'sms',
} as const;
