/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type DeliveryStatus = typeof DeliveryStatus[keyof typeof DeliveryStatus];


export const DeliveryStatus = {
  pending: 'pending',
  sent: 'sent',
  delivered: 'delivered',
  failed: 'failed',
} as const;
