/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { DevicePlatform } from './devicePlatform';

export interface DeviceTokenRegister {
  platform: DevicePlatform;
  /**
   * @minLength 1
   * @maxLength 512
   */
  token: string;
}
