/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { DevicePlatform } from './devicePlatform';

export interface DeviceTokenResponse {
  id: string;
  user_id: string;
  platform: DevicePlatform;
  token: string;
  created_at: string;
  last_used_at: string | null;
}
