/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type DevicePlatform = typeof DevicePlatform[keyof typeof DevicePlatform];


export const DevicePlatform = {
  ios: 'ios',
  ipados: 'ipados',
  macos: 'macos',
} as const;
