/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface DigestTotals {
  total_nags: number;
  completed: number;
  missed: number;
  open: number;
  completion_rate: number;
}
