/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { DigestTotals } from './digestTotals';
import type { MemberSummary } from './memberSummary';

export interface DigestResponse {
  family_id: string;
  period_start: string;
  period_end: string;
  summary_text: string;
  member_summaries: MemberSummary[];
  totals: DigestTotals;
}
