/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type DoneDefinition = typeof DoneDefinition[keyof typeof DoneDefinition];


export const DoneDefinition = {
  ack_only: 'ack_only',
  binary_check: 'binary_check',
  binary_with_note: 'binary_with_note',
} as const;
