/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { EscalationPhase } from './escalationPhase';

export interface EscalationResponse {
  nag_id: string;
  current_phase: EscalationPhase;
  due_at: string;
  computed_at: string;
}
