/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type EscalationPhase = typeof EscalationPhase[keyof typeof EscalationPhase];


export const EscalationPhase = {
  phase_0_initial: 'phase_0_initial',
  phase_1_due_soon: 'phase_1_due_soon',
  phase_2_overdue_soft: 'phase_2_overdue_soft',
  phase_3_overdue_bounded_pushback: 'phase_3_overdue_bounded_pushback',
  phase_4_guardian_review: 'phase_4_guardian_review',
} as const;
