/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type ExcuseCategory = typeof ExcuseCategory[keyof typeof ExcuseCategory];


export const ExcuseCategory = {
  forgot: 'forgot',
  time_conflict: 'time_conflict',
  unclear_instructions: 'unclear_instructions',
  lacking_resources: 'lacking_resources',
  refused: 'refused',
  other: 'other',
} as const;
