/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface FamilyMetricsResponse {
  family_id: string;
  from_date: string | null;
  to_date: string | null;
  total_nags: number;
  completed: number;
  missed: number;
  completion_rate: number;
}
