/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type FamilyRole = typeof FamilyRole[keyof typeof FamilyRole];


export const FamilyRole = {
  guardian: 'guardian',
  child: 'child',
} as const;
