/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type GetFamilyMetricsApiV1ReportsFamilyMetricsGetParams = {
family_id: string;
from_date?: string | null;
to_date?: string | null;
};
