/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { IncentiveApprovalMode } from './incentiveApprovalMode';
import type { IncentiveRuleResponseAction } from './incentiveRuleResponseAction';
import type { IncentiveRuleResponseCondition } from './incentiveRuleResponseCondition';

export interface IncentiveRuleResponse {
  id: string;
  family_id: string;
  version: number;
  condition: IncentiveRuleResponseCondition;
  action: IncentiveRuleResponseAction;
  approval_mode: IncentiveApprovalMode;
  status: string;
}
