/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { IncentiveApprovalMode } from './incentiveApprovalMode';
import type { IncentiveRuleCreateAction } from './incentiveRuleCreateAction';
import type { IncentiveRuleCreateCondition } from './incentiveRuleCreateCondition';

export interface IncentiveRuleCreate {
  family_id: string;
  condition: IncentiveRuleCreateCondition;
  action: IncentiveRuleCreateAction;
  approval_mode?: IncentiveApprovalMode;
}
