/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export interface IncentiveEventResponse {
  id: string;
  nag_id: string;
  rule_id: string;
  action_type: string;
  approved_by: string | null;
  at: string;
}
