/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type IncentiveApprovalMode = typeof IncentiveApprovalMode[keyof typeof IncentiveApprovalMode];


export const IncentiveApprovalMode = {
  auto: 'auto',
  guardian_confirmed: 'guardian_confirmed',
} as const;
