/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { IncentiveApprovalMode } from './incentiveApprovalMode';
import type { IncentiveRuleUpdateAction } from './incentiveRuleUpdateAction';
import type { IncentiveRuleUpdateCondition } from './incentiveRuleUpdateCondition';

export interface IncentiveRuleUpdate {
  condition?: IncentiveRuleUpdateCondition;
  action?: IncentiveRuleUpdateAction;
  approval_mode?: IncentiveApprovalMode | null;
}
