/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type ListNagsApiV1NagsGetParams = {
family_id?: string | null;
connection_id?: string | null;
state?: string | null;
exclude_dismissed?: boolean;
/**
 * @minimum 1
 * @maximum 200
 */
limit?: number;
/**
 * @minimum 0
 */
offset?: number;
};
