/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type ListEventsApiV1GamificationEventsGetParams = {
user_id: string;
family_id?: string | null;
};
