/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type ListBlocksApiV1BlocksGetParams = {
limit?: number;
offset?: number;
};
