/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type MembershipStatus = typeof MembershipStatus[keyof typeof MembershipStatus];


export const MembershipStatus = {
  active: 'active',
  removed: 'removed',
} as const;
