/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { FamilyRole } from './familyRole';

export interface MemberAdd {
  user_id: string;
  role: FamilyRole;
}
