/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { FamilyRole } from './familyRole';

export interface MemberCreateAndAdd {
  /**
   * @minLength 1
   * @maxLength 255
   */
  display_name: string;
  role: FamilyRole;
  username?: string | null;
  pin?: string | null;
}
