/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface MemberSummary {
  user_id: string;
  display_name: string | null;
  total_nags: number;
  completed: number;
  missed: number;
  completion_rate: number;
}
