/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { FamilyRole } from './familyRole';
import type { MembershipStatus } from './membershipStatus';

export interface MemberResponse {
  user_id: string;
  family_id: string;
  role: FamilyRole;
  status: MembershipStatus;
  joined_at: string;
}
