/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { FamilyRole } from './familyRole';
import type { MembershipStatus } from './membershipStatus';

export interface MemberDetail {
  user_id: string;
  display_name: string | null;
  family_id: string;
  role: FamilyRole;
  status: MembershipStatus;
  joined_at: string;
}
