/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface Metric {
  key: string;
  label: string;
  value: number;
  unit: string;
  warn_above?: number | null;
  warn_below?: number | null;
  sparkline_history?: number[] | null;
}
