/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { DoneDefinition } from './doneDefinition';
import type { NagCategory } from './nagCategory';
import type { NagStatus } from './nagStatus';
import type { StrategyTemplate } from './strategyTemplate';

export interface NagResponse {
  id: string;
  family_id: string;
  creator_id: string;
  recipient_id: string;
  due_at: string;
  category: NagCategory;
  done_definition: DoneDefinition;
  description?: string | null;
  strategy_template: StrategyTemplate;
  status: NagStatus;
  created_at: string;
}
