/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type NagStatus = typeof NagStatus[keyof typeof NagStatus];


export const NagStatus = {
  open: 'open',
  completed: 'completed',
  missed: 'missed',
  cancelled_relationship_change: 'cancelled_relationship_change',
  withdrawn: 'withdrawn',
} as const;
