/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { NagStatus } from './nagStatus';

export interface NagStatusUpdate {
  status: NagStatus;
  note?: string | null;
}
