/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { DoneDefinition } from './doneDefinition';
import type { NagCategory } from './nagCategory';

export interface NagUpdate {
  due_at?: string | null;
  category?: NagCategory | null;
  done_definition?: DoneDefinition | null;
}
