/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { MemberDetail } from './memberDetail';

export interface PaginatedResponseMemberDetail {
  items: MemberDetail[];
  total: number;
  limit: number;
  offset: number;
}
