/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { BlockResponse } from './blockResponse';

export interface PaginatedResponseBlockResponse {
  items: BlockResponse[];
  total: number;
  limit: number;
  offset: number;
}
