/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { PolicyResponse } from './policyResponse';

export interface PaginatedResponsePolicyResponse {
  items: PolicyResponse[];
  total: number;
  limit: number;
  offset: number;
}
