/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { ConsentResponse } from './consentResponse';

export interface PaginatedResponseConsentResponse {
  items: ConsentResponse[];
  total: number;
  limit: number;
  offset: number;
}
