/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface PinChangeRequest {
  /**
   * @minLength 4
   * @maxLength 4
   * @pattern ^\d{4}$
   */
  current_pin: string;
  /**
   * @minLength 4
   * @maxLength 4
   * @pattern ^\d{4}$
   */
  new_pin: string;
}
