/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { CompletionFactor } from './completionFactor';

export interface PredictCompletionResponse {
  nag_id: string;
  likelihood: number;
  suggested_reminder_time: string | null;
  factors: CompletionFactor[];
}
