/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { PreferenceResponsePrefsJson } from './preferenceResponsePrefsJson';

export interface PreferenceResponse {
  user_id: string;
  family_id: string;
  schema_version: number;
  prefs_json: PreferenceResponsePrefsJson;
  etag: string;
  updated_at: string;
}
