/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { AITone } from './aITone';

export interface PushBackResponse {
  nag_id: string;
  should_push_back: boolean;
  message: string | null;
  tone: AITone | null;
  reason: string;
}
