/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type Recurrence = typeof Recurrence[keyof typeof Recurrence];


export const Recurrence = {
  every_5_minutes: 'every_5_minutes',
  every_15_minutes: 'every_15_minutes',
  every_30_minutes: 'every_30_minutes',
  hourly: 'hourly',
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
