/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export type Recurrence = typeof Recurrence[keyof typeof Recurrence];


export const Recurrence = {
  daily: 'daily',
  weekly: 'weekly',
  monthly: 'monthly',
} as const;
