/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { RelationshipStatus } from './relationshipStatus';

export interface RelationshipResponse {
  id: string;
  party_a: string;
  party_b: string;
  status: RelationshipStatus;
}
