/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface SignupRequest {
  email: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  password: string;
  display_name?: string | null;
  date_of_birth?: string | null;
}
