/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */

export type StrategyTemplate = typeof StrategyTemplate[keyof typeof StrategyTemplate];


export const StrategyTemplate = {
  friendly_reminder: 'friendly_reminder',
} as const;
