/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { SyncedAIMediationEvent } from './syncedAIMediationEvent';
import type { SyncedConnection } from './syncedConnection';
import type { SyncedGamificationEvent } from './syncedGamificationEvent';
import type { SyncedNag } from './syncedNag';
import type { SyncedNagEvent } from './syncedNagEvent';

export interface SyncResponse {
  nags: SyncedNag[];
  nag_events: SyncedNagEvent[];
  ai_mediation_events: SyncedAIMediationEvent[];
  gamification_events: SyncedGamificationEvent[];
  connections?: SyncedConnection[];
  server_time: string;
}
