/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface SyncedNag {
  id: string;
  family_id: string;
  creator_id: string;
  recipient_id: string;
  due_at: string;
  category: string;
  done_definition: string;
  description: string | null;
  status: string;
  created_at: string;
}
