/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { SyncedNagEventPayload } from './syncedNagEventPayload';

export interface SyncedNagEvent {
  id: string;
  nag_id: string;
  event_type: string;
  actor_id: string;
  at: string;
  payload: SyncedNagEventPayload;
}
