/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface SyncedGamificationEvent {
  id: string;
  family_id: string;
  user_id: string;
  event_type: string;
  delta_points: number;
  streak_delta: number;
  at: string;
}
