/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface SyncedAIMediationEvent {
  id: string;
  nag_id: string;
  prompt_type: string;
  tone: string;
  summary: string;
  at: string;
}
