/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { AITone } from './aITone';

export interface ToneSelectResponse {
  nag_id: string;
  tone: AITone;
  miss_count_7d: number;
  streak: number;
  reason: string;
}
