/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */

export interface TrustedConnectionChild {
  user_id: string;
  display_name?: string | null;
  family_id: string;
  family_name: string;
  connection_id: string;
}
