/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type { ValidationErrorCtx } from './validationErrorCtx';

export interface ValidationError {
  loc: (string | number)[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}
