/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type { WeeklyReportResponseMetrics } from './weeklyReportResponseMetrics';

export interface WeeklyReportResponse {
  family_id: string;
  period_start: string;
  metrics: WeeklyReportResponseMetrics;
}
