/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  DeviceTokenRegister,
  DeviceTokenResponse,
  ListDevicesApiV1DevicesGetParams,
  PaginatedResponseDeviceTokenResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getDevices = () => {
/**
 * Register a device token for push notifications.
 * @summary Register Device
 */
const registerDeviceApiV1DevicesPost = (
    deviceTokenRegister: DeviceTokenRegister,
 ) => {
      return customInstance<DeviceTokenResponse>(
      {url: `/api/v1/devices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: deviceTokenRegister
    },
      );
    }
  /**
 * List the current user's registered device tokens.
 * @summary List Devices
 */
const listDevicesApiV1DevicesGet = (
    params?: ListDevicesApiV1DevicesGetParams,
 ) => {
      return customInstance<PaginatedResponseDeviceTokenResponse>(
      {url: `/api/v1/devices`, method: 'GET',
        params
    },
      );
    }
  /**
 * Unregister a device token.
 * @summary Unregister Device
 */
const unregisterDeviceApiV1DevicesDeviceIdDelete = (
    deviceId: string,
 ) => {
      return customInstance<void>(
      {url: `/api/v1/devices/${deviceId}`, method: 'DELETE'
    },
      );
    }
  return {registerDeviceApiV1DevicesPost,listDevicesApiV1DevicesGet,unregisterDeviceApiV1DevicesDeviceIdDelete}};
export type RegisterDeviceApiV1DevicesPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDevices>['registerDeviceApiV1DevicesPost']>>>
export type ListDevicesApiV1DevicesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDevices>['listDevicesApiV1DevicesGet']>>>
export type UnregisterDeviceApiV1DevicesDeviceIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getDevices>['unregisterDeviceApiV1DevicesDeviceIdDelete']>>>
