/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  BadgeResponse,
  GamificationSummary,
  GetLeaderboardApiV1GamificationLeaderboardGetParams,
  GetSummaryApiV1GamificationSummaryGetParams,
  LeaderboardResponse,
  ListBadgesApiV1GamificationBadgesGetParams,
  ListEventsApiV1GamificationEventsGetParams,
  PaginatedResponseGamificationEventResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getGamification = () => {
/**
 * GET /gamification/summary?family_id={familyId} — member, requires gamification_enabled preference.
 * @summary Get Summary
 */
const getSummaryApiV1GamificationSummaryGet = (
    params: GetSummaryApiV1GamificationSummaryGetParams,
 ) => {
      return customInstance<GamificationSummary>(
      {url: `/api/v1/gamification/summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /gamification/leaderboard?family_id={familyId} — member, requires gamification_enabled preference.
 * @summary Get Leaderboard
 */
const getLeaderboardApiV1GamificationLeaderboardGet = (
    params: GetLeaderboardApiV1GamificationLeaderboardGetParams,
 ) => {
      return customInstance<LeaderboardResponse>(
      {url: `/api/v1/gamification/leaderboard`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /gamification/events?user_id={userId} — member, self-or-guardian.
 * @summary List Events
 */
const listEventsApiV1GamificationEventsGet = (
    params: ListEventsApiV1GamificationEventsGetParams,
 ) => {
      return customInstance<PaginatedResponseGamificationEventResponse>(
      {url: `/api/v1/gamification/events`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /gamification/badges?user_id={userId}&family_id={familyId} — member.
 * @summary List Badges
 */
const listBadgesApiV1GamificationBadgesGet = (
    params: ListBadgesApiV1GamificationBadgesGetParams,
 ) => {
      return customInstance<BadgeResponse[]>(
      {url: `/api/v1/gamification/badges`, method: 'GET',
        params
    },
      );
    }
  return {getSummaryApiV1GamificationSummaryGet,getLeaderboardApiV1GamificationLeaderboardGet,listEventsApiV1GamificationEventsGet,listBadgesApiV1GamificationBadgesGet}};
export type GetSummaryApiV1GamificationSummaryGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['getSummaryApiV1GamificationSummaryGet']>>>
export type GetLeaderboardApiV1GamificationLeaderboardGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['getLeaderboardApiV1GamificationLeaderboardGet']>>>
export type ListEventsApiV1GamificationEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['listEventsApiV1GamificationEventsGet']>>>
export type ListBadgesApiV1GamificationBadgesGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['listBadgesApiV1GamificationBadgesGet']>>>
