/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  GamificationEventResponse,
  GetLeaderboardApiV1GamificationLeaderboardGetParams,
  GetSummaryApiV1GamificationSummaryGetParams,
  ListEventsApiV1GamificationEventsGetParams
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getGamification = () => {
/**
 * GET /gamification/summary?family_id={familyId} — member, requires gamification_enabled preference.
 * @summary Get Summary
 */
const getSummaryApiV1GamificationSummaryGet = (
    params: GetSummaryApiV1GamificationSummaryGetParams,
 ) => {
      return customInstance<unknown>(
      {url: `/api/v1/gamification/summary`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /gamification/leaderboard?family_id={familyId} — member, requires gamification_enabled preference.
 * @summary Get Leaderboard
 */
const getLeaderboardApiV1GamificationLeaderboardGet = (
    params: GetLeaderboardApiV1GamificationLeaderboardGetParams,
 ) => {
      return customInstance<unknown>(
      {url: `/api/v1/gamification/leaderboard`, method: 'GET',
        params
    },
      );
    }
  /**
 * GET /gamification/events?user_id={userId} — member, self-or-guardian.
 * @summary List Events
 */
const listEventsApiV1GamificationEventsGet = (
    params: ListEventsApiV1GamificationEventsGetParams,
 ) => {
      return customInstance<GamificationEventResponse[]>(
      {url: `/api/v1/gamification/events`, method: 'GET',
        params
    },
      );
    }
  return {getSummaryApiV1GamificationSummaryGet,getLeaderboardApiV1GamificationLeaderboardGet,listEventsApiV1GamificationEventsGet}};
export type GetSummaryApiV1GamificationSummaryGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['getSummaryApiV1GamificationSummaryGet']>>>
export type GetLeaderboardApiV1GamificationLeaderboardGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['getLeaderboardApiV1GamificationLeaderboardGet']>>>
export type ListEventsApiV1GamificationEventsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getGamification>['listEventsApiV1GamificationEventsGet']>>>
