/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  ApprovalCreate,
  ApprovalResponse,
  ListApprovalsApiV1PoliciesPolicyIdApprovalsGetParams,
  PaginatedResponseApprovalResponse,
  PolicyResponse,
  PolicyUpdate
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getPolicies = () => {
/**
 * GET /policies/{policyId} — guardian_only.
 * @summary Get Policy
 */
const getPolicyApiV1PoliciesPolicyIdGet = (
    policyId: string,
 ) => {
      return customInstance<PolicyResponse>(
      {url: `/api/v1/policies/${policyId}`, method: 'GET'
    },
      );
    }
  /**
 * PATCH /policies/{policyId} — guardian_only.
 * @summary Update Policy
 */
const updatePolicyApiV1PoliciesPolicyIdPatch = (
    policyId: string,
    policyUpdate: PolicyUpdate,
 ) => {
      return customInstance<PolicyResponse>(
      {url: `/api/v1/policies/${policyId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: policyUpdate
    },
      );
    }
  /**
 * POST /policies/{policyId}/approvals — guardian_only co-owner.
 * @summary Create Approval
 */
const createApprovalApiV1PoliciesPolicyIdApprovalsPost = (
    policyId: string,
    approvalCreate: ApprovalCreate,
 ) => {
      return customInstance<ApprovalResponse>(
      {url: `/api/v1/policies/${policyId}/approvals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: approvalCreate
    },
      );
    }
  /**
 * GET /policies/{policyId}/approvals — guardian_only.
 * @summary List Approvals
 */
const listApprovalsApiV1PoliciesPolicyIdApprovalsGet = (
    policyId: string,
    params?: ListApprovalsApiV1PoliciesPolicyIdApprovalsGetParams,
 ) => {
      return customInstance<PaginatedResponseApprovalResponse>(
      {url: `/api/v1/policies/${policyId}/approvals`, method: 'GET',
        params
    },
      );
    }
  return {getPolicyApiV1PoliciesPolicyIdGet,updatePolicyApiV1PoliciesPolicyIdPatch,createApprovalApiV1PoliciesPolicyIdApprovalsPost,listApprovalsApiV1PoliciesPolicyIdApprovalsGet}};
export type GetPolicyApiV1PoliciesPolicyIdGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['getPolicyApiV1PoliciesPolicyIdGet']>>>
export type UpdatePolicyApiV1PoliciesPolicyIdPatchResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['updatePolicyApiV1PoliciesPolicyIdPatch']>>>
export type CreateApprovalApiV1PoliciesPolicyIdApprovalsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['createApprovalApiV1PoliciesPolicyIdApprovalsPost']>>>
export type ListApprovalsApiV1PoliciesPolicyIdApprovalsGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getPolicies>['listApprovalsApiV1PoliciesPolicyIdApprovalsGet']>>>
