/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.1.0
 */
import type {
  AccountCreate,
  AccountResponse
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getAccounts = () => {
/**
 * POST /accounts — authenticated registration flow.
 * @summary Create Account
 */
const createAccountApiV1AccountsPost = (
    accountCreate: AccountCreate,
 ) => {
      return customInstance<AccountResponse>(
      {url: `/api/v1/accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountCreate
    },
      );
    }
  /**
 * DELETE /accounts/{userId} — self_or_guardian with policy rules.
 * @summary Delete Account
 */
const deleteAccountApiV1AccountsUserIdDelete = (
    userId: string,
 ) => {
      return customInstance<AccountResponse>(
      {url: `/api/v1/accounts/${userId}`, method: 'DELETE'
    },
      );
    }
  return {createAccountApiV1AccountsPost,deleteAccountApiV1AccountsUserIdDelete}};
export type CreateAccountApiV1AccountsPostResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['createAccountApiV1AccountsPost']>>>
export type DeleteAccountApiV1AccountsUserIdDeleteResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getAccounts>['deleteAccountApiV1AccountsUserIdDelete']>>>
