/**
 * Generated by orval v8.3.0 🍺
 * Do not edit manually.
 * Nagz API
 * Family-oriented AI-mediated nagging system
 * OpenAPI spec version: 0.2.0
 */
import type {
  LegalDocument
} from '../../model';

import { customInstance } from '../../axios-instance';



  export const getLegal = () => {
/**
 * GET /legal/privacy-policy — returns the current privacy policy. No auth required.
 * @summary Get Privacy Policy
 */
const getPrivacyPolicyApiV1LegalPrivacyPolicyGet = (
    
 ) => {
      return customInstance<LegalDocument>(
      {url: `/api/v1/legal/privacy-policy`, method: 'GET'
    },
      );
    }
  /**
 * GET /legal/terms-of-service — returns the current terms of service. No auth required.
 * @summary Get Terms Of Service
 */
const getTermsOfServiceApiV1LegalTermsOfServiceGet = (
    
 ) => {
      return customInstance<LegalDocument>(
      {url: `/api/v1/legal/terms-of-service`, method: 'GET'
    },
      );
    }
  return {getPrivacyPolicyApiV1LegalPrivacyPolicyGet,getTermsOfServiceApiV1LegalTermsOfServiceGet}};
export type GetPrivacyPolicyApiV1LegalPrivacyPolicyGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLegal>['getPrivacyPolicyApiV1LegalPrivacyPolicyGet']>>>
export type GetTermsOfServiceApiV1LegalTermsOfServiceGetResult = NonNullable<Awaited<ReturnType<ReturnType<typeof getLegal>['getTermsOfServiceApiV1LegalTermsOfServiceGet']>>>
